# Only meant for building service images
version: '3'
services:
  control:
    build:
      context: ..
      dockerfile: docker/control/Dockerfile
    image: ansible_sandbox/control
  compute:
    build:
      context: .
      dockerfile: docker/compute/Dockerfile
    image: ansible_sandbox/control
  db:
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    image: ansible_sandbox/db_compute
  openstack:
    build:
      context: ..
      dockerfile: docker/openstack/Dockerfile
    image: ansible_sandbox/openstack
