version: '3'
services:
  control:
    build:
      context: ..
      dockerfile: docker/control/Dockerfile
    container_name: control
    image: ansible_sandbox/control
    volumes:
      - "../ansible:/etc/ansible"
  db:
    build:
      context: ..
      dockerfile: docker/supervisor/Dockerfile
    container_name: supervisor
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
    image: ansible_sandbox/db_compute
    ports:
      - "3307:3306"
